# Generated by Django 2.2.1 on 2019-05-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('director', models.CharField(max_length=1000)),
                ('actors', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=1000)),
                ('length', models.IntegerField()),
                ('score', models.FloatField()),
                ('genre', models.CharField(max_length=1000)),
                ('img_url', models.CharField(max_length=1000)),
            ],
        ),
    ]
